Create basic page for the root endpoint
AppFolioOnboarding/image-sharer-sauhardar pull request #1
Opened 2021-01-13 17:40 UTC by sauhardar

2021-01-13 17:57 UTC, infiniteluke requested changes

2021-01-13 17:57 UTC, infiniteluke commented on test/controllers/application_controller_test.rb
> +end
EOF should have a new line

2021-01-13 17:57 UTC, infiniteluke commented on app/views/application/home.html.erb
> +hello from application#home
EOF should have a new line

2021-01-13 17:57 UTC, infiniteluke commented on app/controllers/application_controller.rb
> +  def home; end
I think this commit message would be better named "Setup home controller and placeholder template" or something like that.

2021-01-13 17:57 UTC, infiniteluke commented on test/controllers/application_controller_test.rb
> +end
It seems like this commit could actually be squashed up into the last commit. We try to keep each commit working and fully tested. We try to avoid intermediary commits.

2021-01-14 16:37 UTC, eldonchen0501 approved these changes
LGTM

2021-01-14 16:40 UTC, merged